initial commit

diff --git a/create-24h-movie b/create-24h-movie
--- a/create-24h-movie
+++ b/create-24h-movie
@@ -10,41 +10,64 @@
 # move the movie files to ~/movies
 # delete the directory
 
+MOVIES=${MOVIES:-~/movies}
+LOGLEVEL=${LOGLEVEL:-error}
+
 if [ -z "$1" ]; then
+	echo error: no parameter given!
 	echo need directory to chdir
 	echo exit
 	exit
 fi
 
-echo change dir to $1
+if [ ! -d "$1" ]; then
+	echo $1 is not a directory or doesn\'t exist
+	echo exit
+	exit
+fi
+
+# echo change into dir $1
 cd $1
+MONTH=$(date -d "$(basename $(pwd))" +"%m-%B")
+# echo $MONTH
 
 # we're called like this
-# find -type d | egrep '.*/2017[[:digit:]]{4}$'|xargs -l process-exif-dir
+# find -type d | egrep '.*/2017[[:digit:]]{4}$'|xargs -l create-24h-movie
 
-process-tl-dir -i 120
-cd exif*
+process-tl-dir -i 120 -v 0
 
-mkmov vp9 -w 320 -q 23
-mkdir -p ~/movies/small
-mv -v *.webm ~/movies/small
+if [ $? -ne 0 ]; then
+	echo "couldn't process pictures"
+	exit
+fi
 
-mkmov vp9 -w 1280 -b 500k -2
-mkdir -p ~/movies/webm
-mv -v *.webm ~/movies/webm
+# find really the latest exif-*
+EXIF=$(find -type d -name 'exif-*' -cmin -10 -printf '%f')
+cd $EXIF
 
-mkmov x264 -w 1280 -b 500k -2
-mkdir -p ~/movies/x264
-mv -v *.mp4 ~/movies/x264
+mkdir -p $MOVIES/$MONTH/small/{webm,hevc}
+mkmov vp9 -w 640 -q 26 -b 500k -2 -v $LOGLEVEL -r 25
+mv -v *.webm $MOVIES/$MONTH/small/webm
+mkmov hevc -w 640 -b 500k -2 -v $LOGLEVEL -r 25
+mv -v *.mp4 $MOVIES/$MONTH/small/hevc
 
-mkmov hevc -w 1280 -b 500k -2 
-mkdir -p ~/movies/x265
-mv -v *.mp4 ~/movies/x265
+mkmov vp9 -w 1920 -b 3500k -2 -v $LOGLEVEL -r 25
+mkdir -p $MOVIES/$MONTH/webm
+mv -v *.webm $MOVIES/$MONTH/webm
 
-mkmov hevc -w 1920
-mkdir -p ~/movies/hq
-mv -v *.mp4 ~/movies/hq
+#mkmov x264 -w 1920 -b 3500k -2 -v $LOGLEVEL -r 25
+#mkdir -p $MOVIES/$MONTH/x264
+#mv -v *.mp4 $MOVIES/$MONTH/x264
+
+mkmov hevc -w 1920 -b 3500k -2  -v $LOGLEVEL -r 25
+mkdir -p $MOVIES/$MONTH/x265
+mv -v *.mp4 $MOVIES/$MONTH/x265
+
+mkmov hevc -w 1920 -v $LOGLEVEL -r 25
+mkdir -p $MOVIES/$MONTH/hq
+mv -v *.mp4 $MOVIES/$MONTH/hq
 
 cd ..
-rm -rf exif*
+echo remove $EXIF
+rm -rf $EXIF
 
