weather overlay for pictures from GoC Weather Office

diff --git a/create-24h-movie b/create-24h-movie
--- a/create-24h-movie
+++ b/create-24h-movie
@@ -10,14 +10,17 @@
 # move the movie files to ~/movies
 # delete the directory
 
+set -x
+
 MOVIES=${MOVIES:-~/movies}
-LOGLEVEL=${LOGLEVEL:-error}
 INTERVAL=${INTERVAL:-120} # in seconds
+LOGLEVEL=${LOGLEVEL:-error}
 RATE=${RATE:-30} # frame rate 25 PAL, 30 NTSC
-if [ -z "$PS1" ]; then # running interactive
+VERBOSE=${VERBOSE:0} 
+
+if [ "$VERBOSE" = "0" ]; then
   VERBOSE=1
-else
-  VERBOSE=0
+  LOGLEVEL=info
 fi
 
 echo "effective paramaters:"
@@ -48,8 +51,11 @@ MONTH=$(date -d "$(basename $(pwd))" +"%m-%B")
 
 process-tl-dir -i $INTERVAL -v $VERBOSE
 
-if [ $? -ne 0 ]; then
-	echo "couldn't process pictures"
+rc=$?
+
+if [ $rc -ne 0 ]; then
+  echo "process-tl-dir returned $rc"
+  echo "$(pwd): couldn't process pictures"
 	exit
 fi
 
diff --git a/mkmov b/mkmov
--- a/mkmov
+++ b/mkmov
@@ -1,7 +1,11 @@
 #!/bin/bash
 #
 
-renice -n 10 $$
+if [ -n "$DEBUG" ]; then
+  set -x
+fi
+
+renice -n 10 $$      # reduce priority
 
 START_TIME=$SECONDS
 
@@ -21,18 +25,17 @@ if [ "-"  = "${1:0:1}" ]; then
   exit
 fi
 
-if [ "-"  = "${1:0:1}" ]; then
-  echo first parameter has to be x264, hevc or vp9
-  exit
-fi
-
 CODEC=$1
 if  [ "$CODEC" != "iphone" ]; then
-	FDATE=$(stat -c"%y" tl000001.jpg|cut -b1-10)
-	DATUM=$(stat -c"%y" tl000001.jpg|cut -b1-10|perl -npe "s/(\d+)\-(\d+)\-(\d+)/\3.\2.\1/")
-	# echo "couldn't find tl000001.jpg"
-	# echo "wrong directory?"
-	# exit
+    stat tl000001.jpg
+  if [ $? -eq 0 ]; then
+    FDATE=$(stat -c"%y" tl000001.jpg 2> /dev/null |cut -b1-10)
+    DATUM=$(stat -c"%y" tl000001.jpg 2> /dev/null |cut -b1-10|perl -npe "s/(\d+)\-(\d+)\-(\d+)/\3.\2.\1/")
+  else
+    echo "couldn't find tl000001.jpg"
+    echo "wrong directory?"
+    exit
+  fi
 fi
 
 if  [ "$CODEC" == "iphone" ]; then
