first good version

diff --git a/network_monitor b/network_monitor
--- a/network_monitor
+++ b/network_monitor
@@ -1,19 +1,23 @@
 #!/bin/bash
 
-URL=https://mysavvy.teksavvy.com
+TEKSAVVY=mysavvy.teksavvy.com
+GOOGLE=www.google.com
+LOG=$HOME/var/log/network_monitor.log
 
 echo "start at $(date)"
+echo "start at $(date)" >> $LOG
 
 while true
 do
-  curl --head -s $URL > /dev/null
-
-  RC=$?
-
-  if [ $RC -ne 0 ]; then
+  # curl --head -s https://$TEKSAVVY > /dev/null
+  if ping -c 1 -W 1 $TEKSAVVY &> /dev/null; then
+    echo -en "$(date +%H:%M:%S)\r"
+  else
     # couldn't connect to outside world
+    RC=$?
     echo
-    echo "$(date +%Y%m%d-%H%M%S): $(basename $0): curl to $URL failed with exit code $RC"
+    echo "$(date +%Y%m%d-%H%M%S): $(basename $0): ping to $TEKSAVVY failed with rc=$RC"
+    echo "$(date +%Y%m%d-%H%M%S): $(basename $0): ping to $TEKSAVVY failed with rc=$RC" >> $LOG
 
     # check our wifi
     curl --head -s http://192.168.1.1/webpages/login.html > /dev/null
@@ -25,8 +29,6 @@ do
       logger -t $(basename $0) "curl to router failed, Wifi issue?"
     fi
     logger -t $(basename $0)  "curl to $URL failed with exit code $RC"
-  else
-    echo -n .
   fi
   sleep 7
 done
